version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -DskipTests
artifacts:
  files:
    - target/sales-taxes-0.0.1-SNAPSHOT.jar
    - script/
    - appspec.yml